# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 14:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171129_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
