# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 02:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171129_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 11, 30, 2, 28, 48, 266794, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='SelectedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('product_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_list',
            field=models.ManyToManyField(to='main.SelectedProduct'),
        ),
        migrations.AddField(
            model_name='user',
            name='cart_items',
            field=models.ManyToManyField(to='main.SelectedProduct'),
        ),
        migrations.AddField(
            model_name='user',
            name='order_history',
            field=models.ManyToManyField(to='main.Order'),
        ),
    ]
