# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 17:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171130_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 17, 40, 21, 24019, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='cart_items',
            field=models.ManyToManyField(blank='true', null='true', to='main.SelectedProduct'),
        ),
    ]
