# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_orderlist_paid_date'),
        ('main', '0009_auto_20171201_0759'),
    ]

    operations = [
    ]
